n1 = input('Digite seu nick: ')
n2 = input('Digite sua idade: ')
n3 = input('Voçê joga no mobile ou no emulador: ')
print('Olá {} seja bem vindo!' .format(n1))
print('Eu vi aqui que voçê tem {} anos e joga no {}.' .format(n2, n3))
print('Parabens {} voçê foi aprovado! ' .format(n1))