n1 = int(input('Digite um número de dois a dez: '))
print('ok! agora vou multiplicar esse número por 2! ')
print('{} multiplicado por 2: ' .format(n1))
print(n1*2)
print('Agora vamos somar {} por 5: ' .format(n2))
print(n2+5)
